### ISSUE TITLE
ListFindItem called function, cpu 100% on linux arm

### ISSUE THREAD

**Issue by LD-keep** [eclipse-paho/paho.mqtt.c#1044]
<img width="767" alt="微信图片_20210120160302" src="https://user-images.githubusercontent.com/32668236/105144977-003a0d00-5b39-11eb-9dec-2619bd1bac34.png">

**Comment by icraggs** [comment]
You need to provide more information, as described in the issue template, if there is going to be a chance of helping you.  At least one of a test program, scenario and/or library trace to get started.

**Comment by icraggs** [comment]
Oh - if you call destroy while the client is connected or still active (disonnect hasn't completed fully) that's not a good idea.

**Comment by LD-keep** [comment]
> Oh - if you call destroy while the client is connected or still active (disonnect hasn't completed fully) that's not a good idea.

Can the client automatically connect to the network when the network is disconnected?

> You need to provide more information, as described in the issue template, if there is going to be a chance of helping you. At least one of a test program, scenario and/or library trace to get started.

the libary version is 1.3.1
the client platfom is linux armv7

Reconnection mechanism:
After receiving connectlost, call MQTTClient_disconnect every 30 seconds,
Then call MQTTClient_create and MQTTClient_connect until the connection is successful, which eventually leads to this phenomenon

Note: It is easy to happen when the network environment is relatively poor or the network is relatively unstable

**Comment by liuf951204** [comment]
I encountered the same problem as you, armv7, and the same function you called, MQTTClient_create  creates the client, I do not plug in the Internet, then call MQTTClient_connect,, and 100% CPU consumption will appear..    I don't know how to solve it

**Comment by icraggs** [comment]
1) The latest version is 1.3.8.  Upgrading is essential really - some issues like this have been fixed and a lot of others too.

2) You don't need to call disconnect if you've received connectionLost().  It's already disconnected.

3) Don't call create (or disconnect) if the client has disconnected, just call connect again on the same object.  Calling create again is inefficient and unnecessary.   You can call connect in the connectionLost callback.

4) Automatic reconnect is available in the MQTTAsync API, but not MQTTClient.

**Comment by liuf951204** [comment]
> 1. The latest version is 1.3.8.  Upgrading is essential really - some issues like this have been fixed and a lot of others too.
> 2. You don't need to call disconnect if you've received connectionLost().  It's already disconnected.
> 3. Don't call create (or disconnect) if the client has disconnected, just call connect again on the same object.  Calling create again is inefficient and unnecessary.   You can call connect in the connectionLost callback.
> 4. Automatic reconnect is available in the MQTTAsync API, but not MQTTClient.

Hello, I upgraded to version 1.3.8 today, and according to your suggestion, I directly call MQTTClient_connect5 in the connectionlost() function,  but the problem still exists,,100% CPU consumption will appear

**Comment by icraggs** [comment]
So you'll need to attach a client library trace.  Attach a file, don't paste the contents please.  Use the normal level of trace, not maximum.

**Comment by LD-keep** [comment]
Thanks！
Update version 1.3.8, let you know when the test is complete

**Comment by liuf951204** [comment]
Let me elaborate on how I use it.

Platform armv7

Mqtt5.0 encrypted communication with TLS

1. Call mqttclient_ createWithOptions

2. Call mqttclient_ setCallbacks

3. Call mqttclient_ connect5

4. Call mqttclient_ subscribe5

4. Off line reconnection in on_connection_lost()    while(MQTTClient_isConnected(mqtt_client) == 0){MQTTClient_connect5      sleep(30)}




Use mqtt5.0 log - CPU will take up 100% after offline reconnection

export MQTT_ C_ CLIENT_ TRACE_ LEVEL=TRACE_ MED

20210125 212016.473 (3022755008) (1)< MQTTClient_ cycle:2574 (0)

20210125 212016.473 (3022755008) (1)> MQTTClient_ cycle:2486

20210125 212016.473 (3022755008) (2)> Socket_ getRe adySocket:252

20210125 212016.473 (3022755008) (3)> Socket_ conti nueWrites:995

20210125 212016.693 (3022755008) (3)< Socket_ conti nueWrites:1025 (0)

20210125 212016.693 (3022755008) (3)> isReady:226

20210125 212016.693 (3022755008) (3)< isReady:231 (0)

20210125 212016.693 (3022755008) (2)< Socket_ getRe adySocket:328 (0)

20210125 212016.693 (3022755008) (2)> MQTTClient_ retry:2466

20210125 212016.693 (3022755008) (3)> MQTTProtocol_ keepalive:664

20210125 212016.693 (3022755008) (3)< MQTTProtocol_ keepalive:700

20210125 212016.693 (3022755008) (3)> MQTTProtocol_ retry:788

20210125 212016.693 (3022755008) (4)> MQTTProtocol_ retries:714

20210125 212016.693 (3022755008) (4)< MQTTProtocol_ retries:774

20210125 212016.693 (3022755008) (3)< MQTTProtocol_ retry:807

20210125 212016.693 (3022755008) (2)< MQTTClient_ retry:2476

20210125 212016.693 (3022755008) (1)< MQTTClient_ cycle:2574 (0)

20210125 212016.693 (3022755008) (1)> MQTTClient_ cycle:2486

20210125 212016.693 (3022755008) (2)> Socket_ getRe adySocket:252

20210125 212016.693 (3022755008) (3)> Socket_ conti nueWrites:995

20210125 212016.693 (3022755008) (3)< Socket_ conti nueWrites:1025 (0)

20210125 212016.693 (3022755008) (3)> isReady:226

20210125 212016.693 (3022755008) (3)< isReady:231 (0)

20210125 212016.693 (3022755008) (2)< Socket_ getRe adySocket:328 (0)

20210125 212016.803 (3022755008) (2)> MQTTClient_ retry:2466

20210125 212016.803 (3022755008) (3)> MQTTProtocol_ retry:788

20210125 212016.803 (3022755008) (3)< MQTTProtocol_ retry:807

20210125 212016.803 (3022755008) (2)< MQTTClient_ retry:2476

20210125 212016.803 (3022755008) (1)< MQTTClient_ cycle:2574 (0)

20210125 212016.803 (3022755008) (1)> MQTTClient_ cycle:2486

20210125 212016.803 (3022755008) (2)> Socket_ getRe adySocket:252

**Comment by liuf951204** [comment]
I use mqtt3.0 to call mqttclient_ Connect will not have 100% CPU

**Comment by icraggs** [comment]
Please attach any log as a file, rather than pasting the contents.  You need to include the point at which the situation starts, either network breaking or issuing the connect.

**Comment by icraggs** [comment]
I just noticed this: 

       Off line reconnection in on_connection_lost() while(MQTTClient_isConnected(mqtt_client) == 0){MQTTClient_connect5 sleep(30)}

It's a bad idea to have long running processes running in a callback, if that's what you're doing.  It can cause the API to hang up.  What happens if connectionLost gets called again while you're in the loop, for instance?

**Comment by icraggs** [comment]
In the absence of more information, I'm closing this.
