### ISSUE TITLE
Memory leak after QoS 0 messages fill TCP buffer

### ISSUE THREAD

**Issue by JuergenKosel** [eclipse-paho/paho.mqtt.c#373]
Hello,

there is a (potential) memory leak in:
https://github.com/eclipse/paho.mqtt.c/blob/c85e4a2fd6e96ebc35caef99a024d94c9b664ba0/src/MQTTPacket.c#L207

Because the memory allocated for buf is not freed, if `Socket_putdatas()` return `TCPSOCKET_INTERRUPTED`.

In the usual case, the corresponding free is in: 
https://github.com/eclipse/paho.mqtt.c/blob/c85e4a2fd6e96ebc35caef99a024d94c9b664ba0/src/Socket.c#L780

But I am unsure, if this memory is freed, if `Socket_close()` calls `ListRemoveItem(s.write_pending, &socket, intcompare);`

**Comment by JuergenKosel** [comment]
I have modified may embedded application to cyclically debug print the memory used by paho.mqtt.c as it is reported in
```
    heap_info* mqtt_mem = Heap_get_info();
    SYS_OUT("MQTT mem current %ld, max %ld",mqtt_mem->current_size,mqtt_mem->max_size);
```

So I see the following output during normal operation:
```
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205906, FailedCnt 0, Pending 25 maxPending 56
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 1904, max 10768
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205906, FailedCnt 0, Pending 25 maxPending 56
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 1904, max 10768
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205906, FailedCnt 0, Pending 25 maxPending 56
```
And when the brocker gets disconnected from the LAN, the amount of memory allocated by mqtt grows (which is expected):
```
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 19216, max 19264
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 100 maxPending 100
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 19216, max 19264
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 100 maxPending 100
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 19216, max 19264
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 100 maxPending 100
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 37744, max 37792
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 182 maxPending 182
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 37744, max 37792
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 182 maxPending 182
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 37744, max 37792
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 182 maxPending 182
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 45504, max 45504
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 216 maxPending 216
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 56272, max 56320
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 264 maxPending 264
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 56272, max 56320
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 264 maxPending 264
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 56272, max 56320
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 264 maxPending 264
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 74800, max 74848
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 346 maxPending 346
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 74800, max 74848
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 346 maxPending 346
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 74800, max 74848
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 346 maxPending 346
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 93328, max 93376
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 428 maxPending 428
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 93328, max 93376
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 428 maxPending 428
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 93328, max 93376
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 428 maxPending 428
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 111856, max 111904
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 510 maxPending 510
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 111856, max 111904
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 510 maxPending 510
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 111856, max 111904
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 510 maxPending 510
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 125680, max 125680
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 570 maxPending 570
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 130384, max 130432
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 592 maxPending 592
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 130384, max 130432
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205913, FailedCnt 0, Pending 592 maxPending 592
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 129824, max 130432
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205914, FailedCnt 0, Pending 591 maxPending 592
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 68848, max 130432
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205914, FailedCnt 0, Pending 673 maxPending 673
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 24176, max 130432
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205914, FailedCnt 0, Pending 673 maxPending 673
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 24176, max 130432
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205914, FailedCnt 0, Pending 673 maxPending 673
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 26992, max 130432
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205914, FailedCnt 0, Pending 755 maxPending 755
...
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205914, FailedCnt 0, Pending 3912 maxPending 3912
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 136288, max 140176
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@673:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205914, FailedCnt 0, Pending 3937 maxPending 3937
/Firmware/echo/main/CpMainSrv[1042]: writeMqttConnectionState@775:
/Firmware/echo/main/CpMainSrv[1042]: { "MQTT_CONNECTION_STATE" : { "MESSAGE" : "(null)", "STATUS" : "disconnected"}}
/Firmware/echo/main/CpMainSrv[1042]: writeMqttConnectionState@782:
/Firmware/echo/main/CpMainSrv[1042]: PublishCnt 205914, FailedCnt 0, Pending 3937 maxPending 3937
/Firmware/echo/main/CpMainSrv[1042]: writeMqttConnectionState@785:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 136320, max 140176
/Firmware/echo/main/CpMainSrv[1042]: MQTTAsync_connectionLost@438:
/Firmware/echo/main/CpMainSrv[1042]: MQTTAsync_connectionLost: Disconnected from MQTT broker reason (null)
/Firmware/echo/main/CpMainSrv[1042]: EchoMqttMapper_getSentFrames@665:
/Firmware/echo/main/CpMainSrv[1042]: MQTT mem current 136256, max 140176
```

The memory for the data to publish is not released, after paho.mqtt.c has recognized, that the connection to the broker is lost!

**Comment by JuergenKosel** [comment]
After the call of `MQTTAsync_destroy()` I see also a lot of the following:
```
/Firmware/echo/main/CpMainSrv[1042]: paho.mqtt.c: 20171122 140801.124   Content
20171122 140801.124 Heap element size 32, line 766, file /home/klj/echo-sources-git-svn-full/paho.mqtt.c/src/MQTTProtocolClient.c, ptr 0x539ad760
/Firmware/echo/main/CpMainSrv[1042]: paho.mqtt.c: 20171122 140801.124 Heap element size 32, line 766, file /home/klj/echo-sources-git-svn-full/paho.mqtt.c/src/MQTTProtocolClient.c, ptr 0x539ad760
20171122 140801.124   Content
/Firmware/echo/main/CpMainSrv[1042]: paho.mqtt.c: 20171122 140801.124   Content
20171122 140801.124 Heap element size 32, line 766, file /home/klj/echo-sources-git-svn-full/paho.mqtt.c/src/MQTTProtocolClient.c, ptr 0x539adf10
/Firmware/echo/main/CpMainSrv[1042]: paho.mqtt.c: 20171122 140801.124 Heap element size 32, line 766, file /home/klj/echo-sources-git-svn-full/paho.mqtt.c/src/MQTTProtocolClient.c, ptr 0x539adf10
20171122 140801.124   Content
/Firmware/echo/main/CpMainSrv[1042]: paho.mqtt.c: 20171122 140801.124   Content
20171122 140801.124 Heap scan end
```

Therefore I guess, that the memory allocated by the call of `MQTTstrdup()` in `MQTTAsync_send()` is not freed.

**Comment by JuergenKosel** [comment]
In line https://github.com/eclipse/paho.mqtt.c/blob/c85e4a2fd6e96ebc35caef99a024d94c9b664ba0/src/MQTTAsync.c#L1271 explains why only the topic is not freed but the payload.
Should I open another issue, for this 2nd memory leak?

**Comment by icraggs** [comment]
So, to reproduce this some messages should be queued (inflight?) and then the connection broken?  I would like to have a regression test for this so we can be sure it is fixed properly.

Unless there are two separate scenarios (tests) we are talking about, then one issue is enough.

**Comment by JuergenKosel** [comment]
Hello @icraggs ,

the issue occurs under the following condition:
While the client is publishing to the broker (with QoS=0), the broker becomes disconnected.
So this way the TCP send buffer fills and one publish request end with `TCP_SOCKET_INTERRUPTED`.
Finally the mqtt library recognizes, that the socket is unusable and closes it.
Finally the memory stored for the pending write is never freed (and also the topics of the write requests queued behind this one).

So writing a regression test is difficult because the connection to the broker must be ungracefully broken (unplug wire).
I have already tried to suspend and continue the broker:
```
kill -s SIGSTOP `pidof mosquitto`
sleep 130
kill -s SIGCONT `pidof mosquitto`
```
But this did not break the TCP connection. Even if the connection timeout expires. :-(
This means, that the broker must not be localhost!


BTW: I have also tried with QoS=1: This issue occurs only with QoS=0!

Greetings
Juergen

**Comment by JuergenKosel** [comment]
With the commit https://github.com/eclipse/paho.mqtt.c/pull/374/commits/f7fcf5860d784d4c277d9cec4fb4c3fda939f4e3 to amount of not freed memory looks much better. But still not okay:

```
20171123 163154.138 Trying to write to socket 26 for which there is already pending output
20171123 163154.138 Removing subbuffer of 0x103c2824
20171123 163154.138 Removing subbuffer 0: 0x1037f89c
20171123 163154.138 Removing subbuffer 1: 0x103a583c
20171123 163154.138 No subbuffer to remove
20171123 163223.440 Some memory not freed at shutdown, possible memory leak
20171123 163223.440 Heap scan start, total 192 bytes
20171123 163223.440 Heap element size 16, line 95, file /home/klj/echo-sources-git-svn-full/paho.mqtt.c/src/LinkedList.c, ptr 0x103adaf8
20171123 163224.970   Content
20171123 163224.970 Heap element size 16, line 95, file /home/klj/echo-sources-git-svn-full/paho.mqtt.c/src/LinkedList.c, ptr 0x103b4ea0
20171123 163224.970   Content
20171123 163224.970 Heap element size 32, line 215, file /home/klj/echo-sources-git-svn-full/paho.mqtt.c/src/MQTTProtocolClient.c, ptr 0x103bec48
20171123 163224.970   Content
20171123 163224.970 Heap element size 112, line 232, file /home/klj/echo-sources-git-svn-full/paho.mqtt.c/src/MQTTProtocolClient.c, ptr 0x103c1928
20171123 163224.970   Content
20171123 163224.970 Heap element size 16, line 106, file /home/klj/echo-sources-git-svn-full/paho.mqtt.c/src/MQTTProtocolClient.c, ptr 0x103c2598
20171123 163224.970   Content
20171123 163224.970 Heap scan end
```

**Comment by icraggs** [comment]
I already have a proxy in the test suite which can break the connection (close the socket).  That could do it.

Maybe it doesn't happen with QoS 1/2 because it's easy to limit the number of inflight messages using acks.

So these messages are "queued" in the TCP socket buffer, not the client library?

**Comment by icraggs** [comment]
The client library can not recognize that the connection is broken if all the system calls are still returning success.  The only other way is through the keep alive timeout.

**Comment by JuergenKosel** [comment]
The message are queued by the client library in the TCP send buffer, when it uses the writev() call.
So the problem occurs when the library can not queue anymore data into the TCP send buffer.
And then the library gets the connection lost event of the socket.

For QoS it looks similar, with the exception that the messages are send after the connection is established again.
Maybe I have forgotten to write that my application cyclically calls `MQTTAsync_connect()`, so that a new connection to the brocker (with another socket) is could be established.
So the main difference for QoS=1 and 0 is, that the queued publish messages are send for QoS=1 after reconnect. And for QoS=0 these message are not send, so that their topics are not freed!

**Comment by icraggs** [comment]
Are you using TLS?  How did you first notice the memory leak?

**Comment by JuergenKosel** [comment]
Hello,

TLS is not in use.
It happens on an embedded device, publishing about 80 topics / second.
The application frequently crashed due to the issue fixed in #362 or reaped by the Linux oom-killer.
Both problems occur. So if we would have some kind of regression test, it will trigger 2 problems.

**Comment by icraggs** [comment]
There wasn't a fix in #362 as far as I know - is that the correct one?

**Comment by JuergenKosel** [comment]
Ups, I have used the wrong number.
I meant my own pull request #357 .

**Comment by icraggs** [comment]
I've just tried various test approaches with a proxy and without with limited success so far.  If I send a rapid succession of messages and then kill the broker I can get these:

Heap element size 32, line 751, file src/MQTTAsync.c, ptr 0x7fa3fcb331e0
20171124 122232.126   

The line number corresponds to the current state of master so probably corresponds to the same as yours.  Was this the only memory reference shown in your original problem?  

I want to be clear on what the problem is - it's difficult to assess fixes otherwise.

**Comment by JuergenKosel** [comment]
Hello @icraggs 

in my test I saw many references of MQTTstrdup(), which is called in line 2731 of MQTTAsync.c (master) to copy the topic of the message to publish.

**Comment by JuergenKosel** [comment]
Did you restart the broker and reconnect the client in your test?

**Comment by icraggs** [comment]
So far, it's just stopping.

**Comment by JuergenKosel** [comment]
The library behaves different, if the application calls MQTTAsync_Destroy() shortly after the disconnect from the broker.
- In this case the send failure callbacks of my application is called by some cleanup code in the library.
But in the other case, the connection is reestablished, and some queued messages could be send, then the continue to send / cleanup seems not to work for QoS=0 !

**Comment by icraggs** [comment]
In the simple case, now, the application is calling destroy. 

The behaviour for QoS 0 should be different.  QoS 1 and 2 messages will be retried on restart as the MQTT protocol expects them to be delivered.  However, there is no obligation to resend QoS 0 messages.

I'm working on a test, although the exact scenario of filling up the TCP buffer may not be possible to recreate.

**Comment by JuergenKosel** [comment]
`MQTTAsync_terminate()` calls the `MQTTAsync_freeCommand1()`:
https://github.com/eclipse/paho.mqtt.c/blob/c85e4a2fd6e96ebc35caef99a024d94c9b664ba0/src/MQTTAsync.c#L559
So all outstanding messages to publish are cleaned up.
But in case of reconnect, there is no call of `MQTTAsync_freeCommand1()`. Because the already queued messages should be send (at least for QoS >= 1).
Unfortunally, there is no (re)send or clean up for the QoS=0 message. They are just forgotten. Even the references are lost.

**Comment by icraggs** [comment]
I'm going to attempt anl analysis of memory allocation and frees, in conjunction with testing.

I need to know exactly what symptoms you see, without any of your own changes, as I'm a bit confused by all the information.  Or I can go from the results of my own testing. 

QoS 0 publications should be queued until a TCP send is attempted.  Once a TCP send is attempted, it will not be reattempted (the best interpretation of MQTT QoS requirements).  This means, that if a socket gets into a state where a TCP send returns 0, whereas in fact it does not reach the other end, then that message will not be resent.  I don't think there is any other option.  To be certain the message reaches the destination, you have to use QoS > 0.

So, I think the symptoms are:

1) a memory leak (at destroy time?)

2) a "stack overwrite"?  (when does this happen - destroy or some other call?  Do you have any trace, gdb backtrace for instance?)

**Comment by JuergenKosel** [comment]
Hello,

the memory leak is reported by the library at destroy time. But it happened earlier: When the messages to publish are forwarded from the MQTTAsync part into the MQTTProtocoll part, the MQTTAsync part forgets the reference to the topic (DestinationName). (For some reason the topics are handled different than the payload.)
If then a new connection to the broker is established (with CleanSession=0), also the MQTTProtocoll parts forgets that it has to clean up the QoS=0 messages.
As you have already seen with your test, there are also other memory leaks regarding the pending writes.

For the 2nd symptome, the stack overwrite, I had core dumps of my powerpc application. Each of them pointed to the call of writev() in Sockert_writev(). Applying the commits of pull request #357 solved this.

**Comment by icraggs** [comment]
What exact (set of) memory leaks have you seen reported?  It would be useful to know which ones you have seen.

How do you know that the changes in #357 fixed the stack overwrite?  Did you have a way of reproducing the failure regularly and so could prove it?  I don't think I see anything in that PR that would fix a stack overwrite, except for the assertion - but the assertion is not a run time solution. 
This message "Trying to write to socket 26 for which there is already pending output" could be a symptom.

**Comment by JuergenKosel** [comment]
Again: `Socket_writev()` has the following possible return values:

1. rc >= 0 : Number of bytes transmitted
2. rc = SOCKET_ERROR (-1) : Some error occured on the socket, _except_ EAGAIN, EWOULDBLOCK
3. rc = TCPSOCKET_INTERRUPTED (-22): writev() failed with errno = EAGAIN or errno = EWOULDBLOCK
The last case was not handled by the callers of `Socket_writev()`.
At least in function `Socket_continueWrite()` the local `bytes` variable is not iitialized. And so in case of  `Socket_writev()` returning TCPSOCKET_INTERRUPTED a random value in the local `bytes` variable is used. Which causes a stack overwrite in the next call of `Socket_writev()`.

I have added the assertions, to prevent that some future change might cause another stack corruption, if someone uses a to large value for count.

But the real fix is just in commit  2ada1fe326bc98e6ad2da0e286e861a37e12f565 .

Regarding the memory leak, I saw thousands of memory blocks not freed, which were allocated by `MQTTstrdup()`, which is used to duplicate the topic in `MQTTAsync_send()` :
https://github.com/eclipse/paho.mqtt.c/blob/c85e4a2fd6e96ebc35caef99a024d94c9b664ba0/src/MQTTAsync.c#L2731
There are also some single list elements and as you have already seen, memory for the pending write is also not freed some time.

**Comment by icraggs** [comment]
Hi Juergen.  I understand your description, but I don't agree with the first part.  (Yes, some memory blocks are not freed, definitely).  The proof will be in the testing, and fixing, I hope.  I'm working on the tests.

I think that the case of 3 is handled appropriately by the callers of Socket_writev().

EWOULDBLOCK and EAGAIN are reported by Socket_writev() as TCPSOCKET_INTERRUPTED, with a byte count of 0.    This means that the connection is not broken, but the write can be retried, so is buffered.

Socket_writev in continueWrite() always sets bytes to 0 - at least on Linux.  On Windows it looks like  there could be an initialization issue - but I think you aren't using Windows?  Obviously that should be fixed if it's an issue.

**Comment by JuergenKosel** [comment]
In this line bytes is not initialized:
https://github.com/eclipse/paho.mqtt.c/blob/c85e4a2fd6e96ebc35caef99a024d94c9b664ba0/src/Socket.c#L738
And in this line the not initialized value of bytes is used, if Socket_wrtitev() returned TCP_SOCKET_INTERRUPTED
https://github.com/eclipse/paho.mqtt.c/blob/c85e4a2fd6e96ebc35caef99a024d94c9b664ba0/src/Socket.c#L774

**Comment by JuergenKosel** [comment]
@icraggs 
could you please verify, that in this line
https://github.com/eclipse/paho.mqtt.c/blob/c85e4a2fd6e96ebc35caef99a024d94c9b664ba0/src/Socket.c#L809
the return value of `Socket_continueWrite()` is handled correctly?

**Comment by JuergenKosel** [comment]
After reverting my changes (except the extern C declaration of the Heap function for C++),
I see the following not freed memory:
[messages.log](https://github.com/eclipse/paho.mqtt.c/files/1513398/messages.log)

**Comment by icraggs** [comment]
Yes - I can reproduce 

Heap element size 48, line 766, file src/MQTTProtocolClient.c, ptr 0x7fc232c034d0

and 

20171129 103417.836 Heap element size 32, line 751, file src/MQTTAsync.c, ptr 0x7fe345ff4fe0

quite consistently.  So I can focus on those.

**Comment by icraggs** [comment]
We can easily add initialisation of the "bytes" variable in Socket_continueWrite(), and I will do so.  But I don't think it will change any behaviour on Linux at least because Socket_writev() sets

	*bytes = 0L;

on line 430, before it executes the writev, regardless of whether it returns an error or not.

**Comment by icraggs** [comment]
Hi Juergen,

I've made some changes in branch 373 which improve things in my tests.  It would be great if you could try them out.

One change I made stops the attempted write of QoS 0 pubs to a socket which has already returned -1.

Thanks

**Comment by JuergenKosel** [comment]
Hello @icraggs 
with the patch from branch 373 it looks much better. But there are still some buffers not freed:
[not_free.log](https://github.com/eclipse/paho.mqtt.c/files/1517141/not_free.log)

These blocks were already in the list before the 373 branch. So this branch does not introduce another memory leak.

**Comment by JuergenKosel** [comment]
I have modified the trace level, when Socket_putdatas() returns TCPSOCKET_INTERRUPTED:
[connection_lost.log](https://github.com/eclipse/paho.mqtt.c/files/1517317/connection_lost.log)

The potential double free points to this lines:
```
		/* qos 1 and 2 topics are freed in the protocol code when the flows are completed */
		if (command->command.details.pub.destinationName)
			free(command->command.details.pub.destinationName);
```

**Comment by JuergenKosel** [comment]
Here is a more detailed log file (compiled without -DNOSTACKTRACE ): 
[disconnect_with_functionnames.log](https://github.com/eclipse/paho.mqtt.c/files/1517499/disconnect_with_functionnames.log)

**Comment by icraggs** [comment]
Thanks Juergen for all the information.  Ideally I want to reproduce the exact scenario so I can create a test for it.

**Comment by icraggs** [comment]
I've added another commit to the 373 branch, which, for me at least, frees up more of the memory properly on network errors.  There is still some test code in Socket.c, which I will remove when we're done.

**Comment by icraggs** [comment]
So, it's looking good as far as this issue is concerned then?

**Comment by JuergenKosel** [comment]
Hello,

with commit 82275178a0aa132e6fc2ea7fa04dc424053cc36f it looks much better now.
But some QoS publish messages are now freed when MQTTAsync_destroy() is called:

```
paho.mqtt.c: 20171204 091918.684 (1384666272) (0)> MQTTAsync_isConnected:2490
paho.mqtt.c: 20171204 091918.684 (1384666272) (0)< MQTTAsync_isConnected:2495 (0)
~MqttBroker@259: 
delete MQTT async 0x102c7e7c
paho.mqtt.c: 20171204 091918.684 (1384666272) (0)> MQTTAsync_destroy:1625
paho.mqtt.c: 20171204 091918.684 (1384666272)  (1)> MQTTAsync_removeResponsesAndCommands:1556
paho.mqtt.c: 20171204 091918.825 Calling PUBLISH failure for client {cd5984f0-86b4-480e-88fc-32870eb1b7a7}
MQTTAsync_onWriteFailure@628: 
MQTTAsync_onWriteFailure: Failed to publish MQTT to (null) cause: -11
paho.mqtt.c: 20171204 091918.825 1 responses removed for client {cd5984f0-86b4-480e-88fc-32870eb1b7a7}
paho.mqtt.c: 20171204 091918.825 0 commands removed for client {cd5984f0-86b4-480e-88fc-32870eb1b7a7}
```
Before this commit, those messages were declared as failed when the connection was lost.
Now the memory consumed by the mqtt library grows slowly by each disconnect with pending write. (But the memory for this write would be released during MQTTASync_destroy() call. Which may be to late.)
Here is the log of the time when the connection is shutdown and MQTTAsync is called: 
[memleak.log](https://github.com/eclipse/paho.mqtt.c/files/1526230/memleak.log)
And again there are some memory reported.

**Comment by icraggs** [comment]
Thanks.  Is this trace after 1 disconnect/reconnect cycle, or more than 1?  How many cycles?

I think I know what's going on.  I've added some further updates to the 373 branch, although I can't verify them because right now I can't reproduce the exact scenario.  Is it possible for you to provide me with any of your test material so that I might use it?

**Comment by JuergenKosel** [comment]
Hello @icraggs 

it was not the first cycle. I do not know the correct number.
Just now I am writing on a test to reproduce this issue without my embedded device.
I need still some minutes...
