### ISSUE TITLE
connection failed with -1 error

### ISSUE THREAD

**Issue by sw-tt-chandershekharsuthar** [eclipse-paho/paho.mqtt.c#449]
I'm try to publish my data via MQTT in C and I'm use the sample code of ( Paho MQTT C Client Library link [http://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/pubsync.html]) 

and after running code I'm getting Error that "connection failed return code -1 [ MQTTCLIENT_FAILURE ]

**Comment by icraggs** [comment]
For that sample to work, without changes, you need to have an MQTT broker running on localhost listening on port 1883.  If your broker is elsewhere or on another port, you'll need to change the ADDRESS definition in the sample.

**Comment by sw-tt-chandershekharsuthar** [comment]
I already checked my broker connective in MQTTbox and its working very well but whenever im try in IDE that time I'm getting that error

**Comment by sw-tt-chandershekharsuthar** [comment]
I installed ActiveMQ broker in my system and testing with MQTTbox that is working properly but when I'm trying with my codeblocks IDE with same Address Client and Topic at that time I'm getting error "Failed to connect with MQTTCLIENT_FAILURE in return

**Comment by icraggs** [comment]
Can you use an MQTT application outside of codeblocks to see if that can connect?  You could build the C client sample on the command line, download the prebuilt binaries, or use another client like the Paho Java client, or the libmosquitto client.  This would be just to make sure that the server can be connected to.  Or have you verified that already?

**Comment by sw-tt-chandershekharsuthar** [comment]
hello Ian Craggs,
I checked my MQTT application outside of codeblocks in MQTTbox and Its working properly so that mean my  system can work with MQTT (ActiveMQ is my broker) but when I'm testing on C IDE codeblocks its give me that error because of SOCKET_ERROR from "winsock2.h" and for testing socket I did check  socket programming and it is also working good get me some help..!  THANKS

**Comment by icraggs** [comment]
I'm assuming this is resolved.

**Comment by sw-tt-chandershekharsuthar** [comment]
not solved yet I'm still find the solutions but getting nothing
