### ISSUE TITLE
MEMLEAK: No way to work on HIGH_PERFORMANCE mode

### ISSUE THREAD

**Issue by AdrianMoranMontes** [eclipse-paho/paho.mqtt.c#817]
**Describe the bug**
Running a simple main program (with v1.3.1) that creates client, connects it, publishes a message and disconnect, I saw that ASan sanitizer complies with messages like:

`SocketBuffer.c:82:20: runtime error: member access within misaligned address 0x606000000084 for type 'struct socket_queue', which requires 8 byte alignment`

Navigating through the code I see that malloc/realloc/free are redefined in `Heap.h` file, causing this misalignment. But I also see that there is a macro called HIGH_PERFORMANCE to disable heap tracking. Adding such define to the compiler, the misalignment issue is resolved (as expected) but a memory leak appears with asynchronous client. Each time a message is published with QoS 1 or 2, N bytes are leaked, being N the length of the used topic name.

**To Reproduce**
- Run any simple test with an Address Sanitizer to see misalignment complaints.
- Add HIGH_PERFORMANCE macro (`-DHIGH_PERFORMANCE=1`).
- Run simple test (that uses QoS 1 or QoS 2) again with a memory leak detector to see the leaks.

**Expected behavior**
- Heap tracking should not generate misalignment issues.
- Heap tracking is expected to be completely disabled when HIGH_PERFORMANCE macro is used.

**Environment**
 - OS: Ubuntu x64

**Other help**
Different parts of the code in `MQTTAsync.c` specifies that QoS 1 and QoS 2 releases the leaked bytes in the protocol. Going to `MQTTProtocolClient.c` file, in function `MQTTProtocol_storePublication`, such bytes should be released, but `Heap_findItem` function is used to check if the memory is in the heap (this is the only place where `Heap_findItem` function is used in Paho). Obviously, the return of this function is negative, since pure malloc has been used to allocate the memory, so the memory is never freed.

My first thought was to evaluate the QoS level instead of calling `Heap_findItem` function, but the `header` field of `publish` attribute is not set at this point of execution (which I suppose should be).

My second thought was to remove such checking of calling `Heap_findItem` (which works for my simple test program), but I have some doubts if I can always avoid such checking (I see that QoS 0 can also be stored in case of socket error).

**Additional**
`Tree.c` directly uses `mymalloc`/`myfree `alternatives for `malloc`/`free`, so if heap tracking disable is going to be supported, Tree.c file should also be changed.

**Comment by icraggs** [comment]
The second point: yes, should be fixed.

The first: I'm not sure what this misalignment is.  Where does the 8 byte alignment come from - is this platform dependent?  If it's alignment of the structure members, isn't this controlled by the compiler?  

Perhaps it's a matter of reordering the members of the storageElement structure so that, for instance, the ptr member comes first?  Although that seems arbitrary.

**Comment by AdrianMoranMontes** [comment]
Hi Ian, in first place, thank you for your reply.

Regarding alignment, is how data is stored in memory. The normal behavior is to align data within a struct to the biggest member size. I will show you a few simple examples:

```
#include <stdio.h>

typedef struct
{
   void * a;   // 8 bytes
   int b;      // 4 bytes
   char c;     // 1 byte
} dummy;

int main()
{
   int dummy_size = sizeof(dummy);
   printf("Dummy size: %d\n", dummy_size);

   return 0;
}
```

If you execute this code, the result will be:
`Dummy size: 16 `

As you noted, 16 bytes is bigger than the common response of 13 (8 + 4 + 1). This is because the members of the struct are aligned to the size of biggest element. Taking this into account, the struct should be seen as:
```
typedef struct
{
   void * a;   // 8 bytes
   int b;      // 4 bytes
   char c;     // 1 byte
   // 3 bytes of padding
} dummy;
```


Another more illustrative example just changing the order of elements within the struct:

```
typedef struct
{
   int b;      // 4 bytes
   void * a;   // 8 bytes
   char c;     // 1 byte
} dummy;
```

In this case, the result of the program is:
`Dummy size: 24`

This is because we should see the struct as:
```
typedef struct
{
   int b;      // 4 bytes
   // 4 bytes of padding
   void * a;   // 8 bytes
   char c;     // 1 byte
   // 7 bytes of padding
} dummy;
```


If this part is clear, I'm going now to show why the misalignment. Is just a piece of code of function `mymalloc`:
```
	/* Add space for eyecatcher at each end */
	if ((s->ptr = malloc(size + 2*sizeof(int))) == NULL)
	{
		Log(LOG_ERROR, 13, errmsg);
		free(s->file);
		free(s);
		return NULL;
	}
	space += size + 2*sizeof(int);
	*(int*)(s->ptr) = eyecatcher; /* start eyecatcher */
	*(int*)(((char*)(s->ptr)) + (sizeof(int) + size)) = eyecatcher; /* end eyecatcher */
	Log(TRACE_MAX, -1, "Allocating %d bytes in heap at file %s line %d ptr %p\n", (int)size, file, line, s->ptr);
	TreeAdd(&heap, s, space);
	state.current_size += size;
	if (state.current_size > state.max_size)
		state.max_size = state.current_size;
	Thread_unlock_mutex(heap_mutex);
	return ((int*)(s->ptr)) + 1;	/* skip start eyecatcher */
```

As you can see, the misalignment is caused by the `eyecatcher`, since we are including 4 bytes at the begging of `ptr` and at the end of `ptr`. Obviously, adding 4 bytes at the beginning and 4 bytes at the end makes `ptr` multiple of 8 byte, but we are not returning `ptr`, we are returning `ptr` plus 4 bytes, so at "user level", when you access to the returned pointer, you are in the middle of a 8 bytes block.


One last example (using `mymalloc` function of `Heap.h`) (I know I am not releasing the memory allocated, is just to show the misalignment):
```
#include <Heap.h>

typedef struct
{
   char c; // 1 byte
   void * b; // 8 bytes
   int a; // 4 bytes
} dummy;

int main()
{
   int dummy_size = sizeof(dummy);
   printf("Dummy size: %d\n", dummy_size);

   dummy * allocated = (dummy *)malloc(dummy_size);
   allocated->a = 9;
   printf("Value a: %d\n", allocated->a);

   return 0;
}
```

The result of executing this program with ASan sanitizer:
```
Dummy size: 24
main.c:16:17: runtime error: member access within misaligned address 0x604000000014 for type 'struct dummy', which requires 8 byte alignment
0x604000000014: note: pointer points here
  88 88 88 88 be be be be  be be be be be be be be  be be be be be be be be  be be be be be be be be
              ^ 
main.c:17:4: runtime error: member access within misaligned address 0x604000000014 for type 'struct dummy', which requires 8 byte alignment
0x604000000014: note: pointer points here
  88 88 88 88 be be be be  be be be be be be be be  be be be be 09 00 00 00  be be be be be be be be
              ^ 
Value a: 9
```

One misalignment issue by each access to struct. In the error is easy to see how the `eyecatcher` is in the first 4 bytes and the "user" accesses to the middle on a 8 byte block.

To compile this simple main.c test with pure GCC:
`gcc main.c -I PATH_TO_PAHO_SOURCES -fsanitize=address,undefined -LPATH_TO_PAHO_LIB -lPAHO_LIB -pthread -lubsan`

**Comment by icraggs** [comment]
Thank you.  I know what C structure alignment is in the broadest sense - I've been using C since 1988!

Structure alignment is done by the compiler, and will use the natural alignment for the processor.  So as we are now in the age of 64-bit addressing, can I assume that increasing the eyecatcher to 8 bytes will satisfy the ASan sanitizer?

That could have been the lead in for the issue :-)

**Comment by AdrianMoranMontes** [comment]
Sorry Ian, I just wanted to provide a complete overview of the issue.

Regarding your proposed solution, I can confirm it solves misalignment. I update a PR #819 that solves it. However, as I mentioned in the PR, the solution for HIGH_PERFORMANCE mode is still pending.

In my first post I give some advises to reproduce the issue with HIGH_PERFORMANCE macro, but I am not sure how to solve it for all use cases. As I mentioned, the issue is that `MQTTProtocolClient.c` file uses `Heap_findItem` function before releasing allocated memory. I suppose that such verification is done because there is a use case in which it is possible that the memory is not dynamically allocated at that point (¿QoS 0 with `TCP_INTERRUPTED`?). In any case, I do not have enough knowledge of this part of the library to fix it with security,

Best regards Ian,
Adrian

**Comment by AdrianMoranMontes** [comment]
Sorry, I created the PR over master. I closed it and opened new PR (#820) that solves this.

Sorry again.

**Comment by icraggs** [comment]
No need to apologize!  Thanks for the issue and the PR.

**Comment by icraggs** [comment]
I've put a fix into the develop branch to allow HIGH_PERFORMANCE to work.  I've run it on Linux so far, now to see what the CI tests for Mac and Windows do.

**Comment by icraggs** [comment]
Ok, the CI tests passed.  So I think the HIGH_PERFORMANCE mode should now work.  I added a PAHO_HIGH_PERFORMANCE parameter to the CMake build.

**Comment by AdrianMoranMontes** [comment]
Thank you Ian.

**Comment by AdrianMoranMontes** [comment]
Sorry Ian, but I'm still getting the memory leak with HIGH_PERFORMANCE.

Steps followed:

- Checkout to last commit of develop branch (currently your fix to this issue).
- Compile:
```
mkdir build
cd build
cmake -DPAHO_BUILD_STATIC=TRUE -DPAHO_BUILD_SHARED=FALSE -DCMAKE_BUILD_TYPE=DEBUG -DPAHO_HIGH_PERFORMANCE=TRUE ..
make
```

- Compile a sample with pure GCC:
`gcc ../src/samples/MQTTAsync_publish.c -I ../src/ -L./src -lpaho-mqtt3a -pthread`

- Run the program with Valgrind:
```
# valgrind ./a.out
==24401== Memcheck, a memory error detector
==24401== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==24401== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==24401== Command: ./a.out
==24401==
Waiting for publication of Hello World!
on topic MQTT Examples for client with ClientID: ExampleClientPub
Successful connection
Message with token value 1 delivery confirmed
Successful disconnection
==24401==
==24401== HEAP SUMMARY:
==24401==     in use at exit: 14 bytes in 1 blocks
==24401==   total heap usage: 141 allocs, 140 frees, 223,990 bytes allocated
==24401==
==24401== LEAK SUMMARY:
==24401==    definitely lost: 14 bytes in 1 blocks
==24401==    indirectly lost: 0 bytes in 0 blocks
==24401==      possibly lost: 0 bytes in 0 blocks
==24401==    still reachable: 0 bytes in 0 blocks
==24401==         suppressed: 0 bytes in 0 blocks
==24401== Rerun with --leak-check=full to see details of leaked memory
==24401==
==24401== For counts of detected and suppressed errors, rerun with: -v
==24401== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

As you can see, there is a leak of 14 bytes (the length of testing topic `MQTT Examples` plus 1).


Looking at your fix, you set in function `MQTTProtocol_storePublication`, the following guard macro (file `MQTTProtocolClient.c`):
```
#if !defined(NO_HEAP_TRACKING)                                                                                                                                                                                                                                                  
        if (Heap_findItem(publish->topic))                                                                                                                                                                                                                                      
        {                                                                                                                                                                                                                                                                       
                free(publish->topic);                                                                                                                                                                                                                                           
                publish->topic = NULL;                                                                                                                                                                                                                                          
        }                                                                                                                                                                                                                                                                       
#endif   
```

The problem is that the `free` call is needed to release the memory allocated for topic name. If you set the same piece of code as:
```
                free(publish->topic);                                                                                                                                                                                                                                           
                publish->topic = NULL; 
```
Just removing the `NO_HEAP_TRACKING` macro and the call to `Heap_findItem`, the leak disappears, but I am not sure if it is possible to remove such guards (as I mentioned, this is the only point where `Heap_findItem` function is used).









**Extra information:**

If you preffer to run the test with ASan sanitinzer the result is the same.
```
# gcc ../src/samples/MQTTAsync_publish.c -I ../src/ -fsanitize=address,undefined -L./src -lpaho-mqtt3a -pthread -lubsan
# ./a.out
Waiting for publication of Hello World!
on topic MQTT Examples for client with ClientID: ExampleClientPub
Successful connection
Message with token value 1 delivery confirmed
Successful disconnection

=================================================================
==24518==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 14 byte(s) in 1 object(s) allocated from:
    #0 0x7f35543f5b50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x56072b4afa15 in MQTTStrdup /home/adrian/paho.mqtt.c/src/MQTTProtocolClient.c:876
    #2 0x56072b4ac276 in MQTTAsync_send /home/adrian/paho.mqtt.c/src/MQTTAsync.c:3586
    #3 0x56072b4ac3f4 in MQTTAsync_sendMessage /home/adrian/paho.mqtt.c/src/MQTTAsync.c:3623
    #4 0x56072b4a2708 in onConnect (/home/adrian/paho.mqtt.c/build/a.out+0x5708)
    #5 0x56072b4a8bf0 in MQTTAsync_receiveThread /home/adrian/paho.mqtt.c/src/MQTTAsync.c:2278
    #6 0x7f35533de6da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)

SUMMARY: AddressSanitizer: 14 byte(s) leaked in 1 allocation(s).
```

**Comment by icraggs** [comment]
Thanks.  Yes I'm looking at it - we are closer than previously though!

**Comment by icraggs** [comment]
Ok, I think it's all working now - in the develop branch.
